[package]
name = "motiv-streams"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5.6"
rocket = {version = "0.5.0-rc.2", features = ["json"]}
